"""
Dhan API adapter for GEX Analyzer.
Loads credentials from local environment and wraps the Risk-Management dhan_api integration.
"""

import os
import sys
import logging
import time
import threading
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

# Resolve Risk-Management path dynamically to support Mac and VPS
possible_paths = [
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../Risk-Management")),
    "/root/Risk-Management",
    "/Users/radhagopinath/.gemini/antigravity/scratch/Risk-Management"
]

for p in possible_paths:
    if os.path.exists(p) and p not in sys.path:
        sys.path.append(p)

try:
    from dhan_api import DhanAPI
    DHAN_API_AVAILABLE = True
except ImportError as e:
    logger.warning("Could not import DhanAPI from Risk-Management: %s", e)
    DHAN_API_AVAILABLE = False


class DhanAdapter:
    """Wrapper to initialize and call Dhan Option Chain API."""

    _lock = threading.Lock()
    _last_refresh_time = 0.0
    _refresh_cooldown = 120.0  # 2 minutes cooldown to avoid Dhan rate-limiting

    def __init__(self, client_id=None, access_token=None):
        self.client_id = client_id or os.getenv("DHAN_CLIENT_ID", "")
        self.access_token = access_token or os.getenv("DHAN_ACCESS_TOKEN", "")
        self.api = None
        self.is_connected = False

        if not DHAN_API_AVAILABLE:
            logger.warning("Dhan API integration is unavailable (import failed). Falling back to mock data.")
            return

        if not self.client_id or not self.access_token:
            logger.info("Dhan Client ID or Access Token not set in .env. Operating in SIMULATION mode.")
            return

        try:
            logger.info("Initializing Dhan API client...")
            self.api = DhanAPI()
            # Reinitialize with credentials loaded from our local .env
            self.api.reinitialize(self.client_id, self.access_token)
            self.is_connected = True
            logger.info("Dhan API adapter successfully initialized.")
        except Exception as e:
            logger.error("Failed to initialize Dhan API client: %s", e)
            self.is_connected = False

    def get_fallback_expiry(self, index_name="NIFTY") -> str:
        """Calculate the next Thursday (NIFTY/SENSEX) or Wednesday (BANKNIFTY) expiry date."""
        today = datetime.now()
        target_weekday = 2 if index_name.upper() == "BANKNIFTY" else 3
        days_ahead = target_weekday - today.weekday()
        if days_ahead < 0:
            days_ahead += 7
        elif days_ahead == 0:
            if today.hour >= 16:  # After market close, use next week
                days_ahead += 7
        expiry_date = today + timedelta(days=days_ahead)
        return expiry_date.strftime("%Y-%m-%d")

    def attempt_token_refresh(self) -> bool:
        """Attempt to refresh the Dhan API token using token_manager."""
        if not self.api:
            return False

        with DhanAdapter._lock:
            now = time.time()
            # If a refresh was executed in the last 2 minutes, avoid hitting Dhan again
            if now - DhanAdapter._last_refresh_time < DhanAdapter._refresh_cooldown:
                logger.warning("Token was refreshed recently. Skipping API refresh call. Reloading token from disk...")
                
                # Reload env from disk (which contains the token generated by the other thread)
                from dotenv import load_dotenv
                for p in possible_paths:
                    env_path = os.path.join(p, ".env")
                    if os.path.exists(env_path):
                        load_dotenv(env_path, override=True)
                        break
                        
                self.client_id = os.getenv("DHAN_CLIENT_ID", "")
                self.access_token = os.getenv("DHAN_ACCESS_TOKEN", "")
                self.api.reinitialize(self.client_id, self.access_token)
                return True

            try:
                from token_manager import refresh_token, is_token_refresh_configured
                if is_token_refresh_configured():
                    logger.info("Dhan token is invalid. Invoking Risk-Management token_manager to refresh...")
                    success = refresh_token(self.api)
                    if success:
                        DhanAdapter._last_refresh_time = time.time()
                        self.access_token = self.api.access_token
                        logger.info("Successfully refreshed and reinitialized Dhan token!")
                        return True
                else:
                    logger.warning("Auto token refresh is not configured (DHAN_PIN or DHAN_TOTP_SECRET missing)")
            except Exception as e:
                logger.error("Failed to execute token refresh flow: %s", e)
            return False

    def get_expiry_dates(self, index_name="NIFTY"):
        """Get available expiry dates for the selected index."""
        if not self.is_connected or not self.api:
            return [self.get_fallback_expiry(index_name)]

        uid_map = {"NIFTY": 13, "BANKNIFTY": 25, "SENSEX": 1}
        underlying_id = uid_map.get(index_name.upper(), 13)

        try:
            # Bypass the buggy api.get_expiry_list wrapper and query raw API directly
            response = self.api.dhan.expiry_list(
                under_security_id=underlying_id,
                under_exchange_segment=self.api.IDX_I
            )
            
            expiries = []
            if isinstance(response, dict) and "data" in response:
                data = response["data"]
                if isinstance(data, dict) and "data" in data:
                    expiries = data["data"]
                elif isinstance(data, list):
                    expiries = data

            if not expiries:
                logger.warning("Expiry list empty. Attempting token refresh...")
                if self.attempt_token_refresh():
                    response = self.api.dhan.expiry_list(
                        under_security_id=underlying_id,
                        under_exchange_segment=self.api.IDX_I
                    )
                    if isinstance(response, dict) and "data" in response:
                        data = response["data"]
                        if isinstance(data, dict) and "data" in data:
                            expiries = data["data"]
                        elif isinstance(data, list):
                            expiries = data
            
            if not expiries:
                fallback = self.get_fallback_expiry(index_name)
                logger.warning("Dhan returned empty expiry list. Using fallback date: %s", fallback)
                return [fallback]
                
            return sorted(expiries)
        except Exception as e:
            logger.error("Error fetching expiry list from Dhan for %s: %s", index_name, e)
            if self.attempt_token_refresh():
                try:
                    response = self.api.dhan.expiry_list(
                        under_security_id=underlying_id,
                        under_exchange_segment=self.api.IDX_I
                    )
                    expiries = []
                    if isinstance(response, dict) and "data" in response:
                        data = response["data"]
                        if isinstance(data, dict) and "data" in data:
                            expiries = data["data"]
                    if expiries:
                        return sorted(expiries)
                except Exception:
                    pass
            
            fallback = self.get_fallback_expiry(index_name)
            logger.warning("Could not fetch expiries. Using fallback date: %s", fallback)
            return [fallback]

    def get_option_chain_data(self, index_name="NIFTY", expiry_date=""):
        """
        Fetch options chain from Dhan.
        Returns a dict with:
           {
             'spot': float,
             'oc': dict (strike: { 'ce': { 'last_price', 'oi', 'volume', 'gamma' }, ... })
           }
        """
        if not self.is_connected or not self.api:
            return None

        index_name = index_name.upper()
        uid_map = {
            "NIFTY": (13, "IDX_I"),
            "BANKNIFTY": (25, "IDX_I"),
            "SENSEX": (1, "BSE_IDX")
        }
        underlying_id, exchange_segment = uid_map.get(index_name, (13, "IDX_I"))

        if not expiry_date:
            expiries = self.get_expiry_dates(index_name)
            expiry_date = expiries[0] if expiries else self.get_fallback_expiry(index_name)

        try:
            logger.info("Fetching option chain for %s, expiry %s...", index_name, expiry_date)
            result = self.api.get_option_chain(
                underlying_id=underlying_id,
                expiry=expiry_date,
                exchange_segment=exchange_segment
            )

            # Check if query failed (potentially due to stale token) and refresh if needed
            if not isinstance(result, dict) or result.get("status") != "success":
                logger.warning("Dhan option chain query failed. Attempting token refresh...")
                if self.attempt_token_refresh():
                    logger.info("Retrying option chain query with new token...")
                    result = self.api.get_option_chain(
                        underlying_id=underlying_id,
                        expiry=expiry_date,
                        exchange_segment=exchange_segment
                    )

            if not isinstance(result, dict) or result.get("status") != "success":
                logger.error("Dhan option chain returned failure status: %s", result)
                return None

            oc_data = result.get("data", {})
            # Unwrap if double nested
            if isinstance(oc_data, dict) and "data" in oc_data and isinstance(oc_data["data"], dict):
                oc_data = oc_data["data"]

            spot = float(oc_data.get("last_price", 0) or 0)
            raw_oc = oc_data.get("oc", {})

            # Standardize output format
            formatted_oc = {}
            for strike_str, sides in raw_oc.items():
                try:
                    strike = float(strike_str)
                except ValueError:
                    continue

                ce = sides.get("ce", {}) or {}
                pe = sides.get("pe", {}) or {}

                formatted_oc[strike] = {
                    "ce": {
                        "last_price": float(ce.get("last_price", 0) or 0),
                        "oi": int(ce.get("oi", 0) or 0),
                        "volume": int(ce.get("volume", 0) or 0),
                    },
                    "pe": {
                        "last_price": float(pe.get("last_price", 0) or 0),
                        "oi": int(pe.get("oi", 0) or 0),
                        "volume": int(pe.get("volume", 0) or 0),
                    }
                }

            return {
                "spot": spot,
                "chain": formatted_oc
            }

        except Exception as e:
            logger.error("Failed to fetch option chain from Dhan: %s", e)
            return None
